#!/usr/bin/env bash

DIR_BASE="/usr/local"
DIR_BMWI="${DIR_BASE}/bmwi"

DATE_STR="$(date '+%Y%m%d')"

ARRAY_FILES=(
'config.json'
'status-can0.json'
'status-can1.json'
'status-dbus.json'
'status-ibus.json'
'status-kbus.json'
)


[[ ! -d "${DIR_BMWI}" ]] && exit 0

cd "${DIR_BMWI}" || exit 1

mkdir -p json.bak || exit 2

for JSON_FILE in "${ARRAY_FILES[@]}"; do
	[[ ! -s "${JSON_FILE}" ]] && continue
	cp -v "${JSON_FILE}" "json.bak/${JSON_FILE}.${DATE_STR}"
done
